[package]
name = "encrypted-space-data-partition"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["net", "rt", "sync", "io-util", "rt-multi-thread", "macros"] }